name: Deploy to GitHub Pages

on:
  # O deploy será disparado sempre que houver um push no branch 'main'
  push:
    branches:
      - main 

# Permite que o GitHub Action escreva no branch gh-pages
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # O build e deploy rodarão em um servidor do GitHub

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Versão LTS
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build Project
        run: npm run build # Executa o build do Vite, criando a pasta 'dist'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # O branch gh-pages será criado/atualizado
          publish_branch: gh-pages
          # O conteúdo da pasta 'dist' será enviado
          publish_dir: ./dist